[package]
name = "codecrafters-interpreter"
version = "0.1.0"
authors = [
    "Yin-Chi Chan <yinchichan@pm.me>",
    "Codecrafters <hello@codecrafters.io>"
]
edition = "2024"
rust-version = "1.91"

[dependencies]
anyhow = "1.0.68"                                # error handling
bytes = "1.3.0"                                  # helps manage buffers
derive-new = "0.7"                               # derive new() constructors
thiserror = "1.0.38"                             # error handling
